<a href="https://colab.research.google.com/github/PreethamHD/DP-MMFL/blob/main/notebooks/01_dataset_inspection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
import os
import sys

# 1. Remount Google Drive
drive.mount("/content/drive")

# 2. Re-clone repository if the local VM disk was wiped
%cd /content
if not os.path.exists("/content/DP-MMFL"):
    !git clone https://github.com/Preetham-HD/DP-MMFL.git
else:
    %cd /content/DP-MMFL
    !git pull origin main

# 3. Add src directory to Python path
SRC_PATH = "/content/DP-MMFL/src"
if SRC_PATH not in sys.path:
    sys.path.append(SRC_PATH)

print("Workspace restored successfully.")

Mounted at /content/drive
/content
Cloning into 'DP-MMFL'...
fatal: could not read Username for 'https://github.com': No such device or address
Workspace restored successfully.

In [5]:
from google.colab import drive, userdata
import os
import sys

# 1. Mount Google Drive
drive.mount("/content/drive")

# 2. Retrieve token from Colab Secrets
GITHUB_TOKEN = userdata.get("GITHUB_TOKEN")
GITHUB_USERNAME = "PreethamHD"
REPO_NAME = "DP-MMFL"

REPO_URL = f"https://{GITHUB_TOKEN}@github.com/{GITHUB_USERNAME}/DP-MMFL"

# 3. Clone or pull
%cd /content
if not os.path.exists(f"/content/{REPO_NAME}"):
    !git clone {REPO_URL}
else:
    %cd /content/{REPO_NAME}
    !git pull origin main

# 4. Add src directory to Python path
SRC_PATH = f"/content/{REPO_NAME}/src"
if SRC_PATH not in sys.path:
    sys.path.append(SRC_PATH)

print("Workspace restored successfully.")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/content
Cloning into 'DP-MMFL'...
remote: Enumerating objects: 54, done.
remote: Counting objects: 100% (54/54), done.
remote: Compressing objects: 100% (36/36), done.
remote: Total 54 (delta 12), reused 42 (delta 10), pack-reused 0 (from 0)
Receiving objects: 100% (54/54), 13.67 KiB | 700.00 KiB/s, done.
Resolving deltas: 100% (12/12), done.
Workspace restored successfully.

In [6]:
%cd /content/DP-MMFL
!pip install -q -r requirements.txt

/content/DP-MMFL
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 47.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 9.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 983.4/983.4 kB 70.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 455.2/455.2 kB 40.4 MB/s eta 0:00:00

In [40]:
import sys

sys.path.append("/content/DP-MMFL/src")

In [7]:
from pathlib import Path

DATASET_ROOT = Path(
    "/content/drive/MyDrive/DP-MMFL/data/raw/chexpert_plus"
)

print(DATASET_ROOT)

/content/drive/MyDrive/DP-MMFL/data/raw/chexpert_plus

In [8]:
expected_files = [
    "df_chexpert_plus_240401.csv",
    "findings_fixed.json",
    "impression_fixed.json",
    "report_fixed.json",
]

for filename in expected_files:
    path = DATASET_ROOT / filename

    if path.exists():
        size_mb = path.stat().st_size / (1024 ** 2)
        print(f"✓ {filename:<35} {size_mb:,.2f} MB")
    else:
        print(f"✗ MISSING: {filename}")

✓ df_chexpert_plus_240401.csv         386.18 MB
✓ findings_fixed.json                 80.22 MB
✓ impression_fixed.json               79.90 MB
✓ report_fixed.json                   79.81 MB

In [9]:
import pandas as pd

CSV_PATH = DATASET_ROOT / "df_chexpert_plus_240401.csv"

header = pd.read_csv(CSV_PATH, nrows=0)

print("Number of columns:", len(header.columns))
print("\nColumns:")
for i, column in enumerate(header.columns, start=1):
    print(f"{i:2}. {column}")

Number of columns: 27

Columns:
 1. path_to_image
 2. path_to_dcm
 3. frontal_lateral
 4. ap_pa
 5. deid_patient_id
 6. patient_report_date_order
 7. report
 8. section_narrative
 9. section_clinical_history
10. section_history
11. section_comparison
12. section_technique
13. section_procedure_comments
14. section_findings
15. section_impression
16. section_end_of_impression
17. section_summary
18. section_accession_number
19. age
20. sex
21. race
22. ethnicity
23. interpreter_needed
24. insurance_type
25. recent_bmi
26. deceased
27. split

In [10]:
df = pd.read_csv(
    CSV_PATH,
    low_memory=False
)

print("Shape:", df.shape)

Shape: (223462, 27)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 223462 entries, 0 to 223461
Data columns (total 27 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   path_to_image               223462 non-null  object
 1   path_to_dcm                 223462 non-null  object
 2   frontal_lateral             223462 non-null  object
 3   ap_pa                       191071 non-null  object
 4   deid_patient_id             223462 non-null  object
 5   patient_report_date_order   223462 non-null  int64
 6   report                      223462 non-null  object
 7   section_narrative           223434 non-null  object
 8   section_clinical_history    138866 non-null  object
 9   section_history             38192 non-null   object
 10  section_comparison          213125 non-null  object
 11  section_technique           10732 non-null   object
 12  section_procedure_comments  25669 non-null   object
 13  section_findings            59469 non-null   object
 14  section_impression          223317 non-null  object
 15  section_end_of_impression   73738 non-null   object
 16  section_summary             189648 non-null  object
 17  section_accession_number    223462 non-null  object
 18  age                         223184 non-null  float64
 19  sex                         223462 non-null  object
 20  race                        223462 non-null  object
 21  ethnicity                   223462 non-null  object
 22  interpreter_needed          223462 non-null  object
 23  insurance_type              223462 non-null  object
 24  recent_bmi                  164985 non-null  float64
 25  deceased                    223462 non-null  object
 26  split                       223462 non-null  object
dtypes: float64(2), int64(1), object(24)
memory usage: 46.0+ MB

In [12]:
df.head(3)
df.tail(3)

,path_to_image,path_to_dcm,frontal_lateral,ap_pa,deid_patient_id,patient_report_date_order,report,section_narrative,section_clinical_history,section_history,...,section_accession_number,age,sex,race,ethnicity,interpreter_needed,insurance_type,recent_bmi,deceased,split
223459,train/patient64064/study1/view1_frontal.jpg,train/patient64064/study1/view1_frontal.dcm,Frontal,AP,patient64064,1,NARRATIVE:\nSINGLE VIEW OF THE CHEST: 10-30-2...,\nSINGLE VIEW OF THE CHEST: 10-30-2015\n \n,A 62-year-old female with history of subarac...,NaN,...,\n4NW50T38LS778\nThis report has been anonymiz...,62.0,Female,Other,Hispanic/Latino,Yes,Unknown,50.0,No,train
223460,train/patient64079/study1/view1_frontal.jpg,train/patient64079/study1/view1_frontal.dcm,Frontal,AP,patient64079,1,"NARRATIVE:\nPORTABLE CHEST, SINGLE VIEW, 12/17...","\nPORTABLE CHEST, SINGLE VIEW, 12/17/2019 secu...",Trauma.\n,NaN,...,\n555819\nThis report has been anonymized. All...,21.0,Female,Pacific Islander,Non-Hispanic/Non-Latino,No,Private Insurance,50.0,No,train
223461,valid/patient64739/study1/view1_frontal.jpg,valid/patient64739/study1/view1_frontal.dcm,Frontal,AP,patient64739,1,NARRATIVE:\nCOMPARISON: 7-21-2005\n \nIMPRESSI...,\n,NaN,NaN,...,\n64558813\nThis report has been anonymized. A...,45.0,Female,White,Non-Hispanic/Non-Latino,No,Private Insurance,50.0,No,valid

In [13]:
duplicate_rows = df.duplicated().sum()

print("Duplicate rows:", duplicate_rows)

Duplicate rows: 0

In [14]:
missing = (
    df.isna()
      .sum()
      .sort_values(ascending=False)
)

missing_percentage = (
    df.isna()
      .mean()
      .mul(100)
      .sort_values(ascending=False)
)

missing_summary = pd.DataFrame({
    "missing_count": missing,
    "missing_percentage": missing_percentage
})

missing_summary

                            missing_count  missing_percentage
section_technique                  212730           95.197394
section_procedure_comments         197793           88.513036
section_history                    185270           82.908951
section_findings                   163993           73.387422
section_end_of_impression          149724           67.001996
section_clinical_history            84596           37.856996
recent_bmi                          58477           26.168655
section_summary                     33814           15.131879
ap_pa                               32391           14.495082
section_comparison                  10337            4.625842
age                                   278            0.124406
section_impression                    145            0.064888
section_narrative                      28            0.012530
patient_report_date_order               0            0.000000
deid_patient_id                         0            0.000000
path_to_dcm                             0            0.000000
path_to_image                           0            0.000000
report                                  0            0.000000
frontal_lateral                         0            0.000000
section_accession_number                0            0.000000
sex                                     0            0.000000
ethnicity                               0            0.000000
race                                    0            0.000000
interpreter_needed                      0            0.000000
insurance_type                          0            0.000000
deceased                                0            0.000000
split                                   0            0.000000

In [15]:
print("Rows:", len(df))

print(
    "Unique patients:",
    df["deid_patient_id"].nunique()
)

print(
    "Missing patient IDs:",
    df["deid_patient_id"].isna().sum()
)

Rows: 223462
Unique patients: 64725
Missing patient IDs: 0

In [16]:
images_per_patient = (
    df.groupby("deid_patient_id")
      .size()
)

print(images_per_patient.describe())

count    64725.000000
mean         3.452484
std          4.651210
min          1.000000
25%          1.000000
50%          2.000000
75%          4.000000
max         92.000000
dtype: float64

In [17]:
print(
    "Patients with >1 image:",
    (images_per_patient > 1).sum()
)

print(
    "Maximum images for one patient:",
    images_per_patient.max()
)

Patients with >1 image: 41959
Maximum images for one patient: 92

In [18]:
print(df["split"].value_counts(dropna=False))

split
train    223228
valid       234
Name: count, dtype: int64

In [19]:
print(
    "Unique split values:",
    df["split"].unique()
)

Unique split values: ['train' 'valid']

In [20]:
print(df["path_to_image"].head(10).to_string(index=False))

train/patient00003/study1/view1_frontal.jpg
train/patient00007/study2/view1_frontal.jpg
train/patient00007/study1/view1_frontal.jpg
train/patient00009/study1/view2_lateral.jpg
train/patient00009/study1/view1_frontal.jpg
train/patient00016/study1/view2_lateral.jpg
train/patient00016/study1/view1_frontal.jpg
train/patient00021/study1/view1_frontal.jpg
train/patient00026/study1/view1_frontal.jpg
train/patient00026/study1/view2_lateral.jpg

In [21]:
print(
    "Missing image paths:",
    df["path_to_image"].isna().sum()
)

print(
    "Unique image paths:",
    df["path_to_image"].nunique()
)

Missing image paths: 0
Unique image paths: 223462

In [22]:
print(
    "Duplicate image paths:",
    df["path_to_image"].duplicated().sum()
)

Duplicate image paths: 0

In [23]:
print(df["path_to_dcm"].head(10).to_string(index=False))

print(
    "Missing DICOM paths:",
    df["path_to_dcm"].isna().sum()
)

print(
    "Unique DICOM paths:",
    df["path_to_dcm"].nunique()
)

train/patient00003/study1/view1_frontal.dcm
train/patient00007/study2/view1_frontal.dcm
train/patient00007/study1/view1_frontal.dcm
train/patient00009/study1/view2_lateral.dcm
train/patient00009/study1/view1_frontal.dcm
train/patient00016/study1/view2_lateral.dcm
train/patient00016/study1/view1_frontal.dcm
train/patient00021/study1/view1_frontal.dcm
train/patient00026/study1/view1_frontal.dcm
train/patient00026/study1/view2_lateral.dcm
Missing DICOM paths: 0
Unique DICOM paths: 223462

In [24]:
print("frontal_lateral:")
print(df["frontal_lateral"].value_counts(dropna=False))

print("\nap_pa:")
print(df["ap_pa"].value_counts(dropna=False))

frontal_lateral:
frontal_lateral
Frontal    191071
Lateral     32391
Name: count, dtype: int64

ap_pa:
ap_pa
AP     161622
NaN     32391
PA      29432
LL         16
RL          1
Name: count, dtype: int64

In [25]:
report_columns = [
    "report",
    "section_narrative",
    "section_clinical_history",
    "section_history",
    "section_comparison",
    "section_technique",
    "section_procedure_comments",
    "section_findings",
    "section_impression",
    "section_end_of_impression",
    "section_summary",
]

report_missing = pd.DataFrame({
    "missing": df[report_columns].isna().sum(),
    "missing_%": df[report_columns].isna().mean() * 100
})

report_missing.sort_values("missing_%", ascending=False)

                            missing  missing_%
section_technique            212730  95.197394
section_procedure_comments   197793  88.513036
section_history              185270  82.908951
section_findings             163993  73.387422
section_end_of_impression    149724  67.001996
section_clinical_history      84596  37.856996
section_summary               33814  15.131879
section_comparison            10337   4.625842
section_impression              145   0.064888
section_narrative                28   0.012530
report                            0   0.000000

In [26]:
findings_length = (
    df["section_findings"]
      .fillna("")
      .astype(str)
      .str.len()
)

print(findings_length.describe())

count    223462.000000
mean        114.082945
std         226.744033
min           0.000000
25%           0.000000
50%           0.000000
75%         163.000000
max        3397.000000
Name: section_findings, dtype: float64

In [27]:
impression_length = (
    df["section_impression"]
      .fillna("")
      .astype(str)
      .str.len()
)

print(impression_length.describe())

count    223462.000000
mean        302.699260
std         149.811118
min           0.000000
25%         200.000000
50%         280.000000
75%         380.000000
max        2946.000000
Name: section_impression, dtype: float64

In [28]:
print(
    "Empty findings:",
    (findings_length == 0).mean() * 100,
    "%"
)

print(
    "Empty impressions:",
    (impression_length == 0).mean() * 100,
    "%"
)

Empty findings: 73.3874215750329 %
Empty impressions: 0.06488798990432378 %

In [29]:
for column in ["sex", "race", "ethnicity"]:
    print("\n" + "=" * 50)
    print(column)
    print("=" * 50)
    print(df[column].value_counts(dropna=False))

==================================================
sex
==================================================
sex
Male       132482
Female      90701
Unknown       279
Name: count, dtype: int64

==================================================
race
==================================================
race
White               126669
Other                31561
Unknown              25370
Asian                23719
Black                12062
Pacific Islander      3180
Native American        547
Patient Refused        354
Name: count, dtype: int64

==================================================
ethnicity
==================================================
ethnicity
Non-Hispanic/Non-Latino    169886
Hispanic/Latino             28222
Unknown                     24947
Patient Refused               407
Name: count, dtype: int64

In [30]:
print(df["age"].describe())
print("Missing age:", df["age"].isna().sum())

count    223184.000000
mean         60.390938
std          17.770630
min           0.000000
25%          49.000000
50%          62.000000
75%          74.000000
max          89.000000
Name: age, dtype: float64
Missing age: 278

In [31]:
print(
    "Age range:",
    df["age"].min(),
    "to",
    df["age"].max()
)

Age range: 0.0 to 89.0

In [32]:
print(df["recent_bmi"].describe())
print("Missing BMI:", df["recent_bmi"].isna().sum())

count    164985.000000
mean         26.731495
std           6.510710
min           0.000000
25%          22.300000
50%          25.700000
75%          30.000000
max          50.000000
Name: recent_bmi, dtype: float64
Missing BMI: 58477

In [33]:
for column in ["sex", "race", "ethnicity"]:
    consistency = (
        df.groupby("deid_patient_id")[column]
          .nunique(dropna=True)
    )

    print(
        column,
        "patients with >1 value:",
        (consistency > 1).sum()
    )

sex patients with >1 value: 0
race patients with >1 value: 0
ethnicity patients with >1 value: 0

In [34]:
from pathlib import Path

RESULTS_DIR = Path(
    "/content/drive/MyDrive/DP-MMFL/results/metrics"
)

RESULTS_DIR.mkdir(parents=True, exist_ok=True)

inspection_file = RESULTS_DIR / "dataset_inspection.txt"

with open(inspection_file, "w") as f:
    f.write("DP-MMFL — CheXpert Plus Dataset Inspection\n")
    f.write("=" * 60 + "\n\n")
    f.write(f"Rows: {len(df)}\n")
    f.write(f"Columns: {len(df.columns)}\n")
    f.write(
        f"Unique patients: "
        f"{df['deid_patient_id'].nunique()}\n"
    )
    f.write(
        f"Duplicate rows: "
        f"{df.duplicated().sum()}\n"
    )

print(inspection_file)

/content/drive/MyDrive/DP-MMFL/results/metrics/dataset_inspection.txt

In [35]:
import json

JSON_FILES = [
    "findings_fixed.json",
    "impression_fixed.json",
    "report_fixed.json",
]

for filename in JSON_FILES:
    path = DATASET_ROOT / filename

    print("\n" + "=" * 70)
    print(filename)
    print("=" * 70)

    with open(path, "r") as f:
        for i in range(2):
            line = f.readline()
            record = json.loads(line)
            print(record)

======================================================================
findings_fixed.json
======================================================================
{'path_to_image': 'train/patient42142/study5/view1_frontal.jpg', 'Enlarged Cardiomediastinum': None, 'Cardiomegaly': None, 'Lung Opacity': None, 'Lung Lesion': None, 'Edema': None, 'Consolidation': None, 'Pneumonia': None, 'Atelectasis': None, 'Pneumothorax': None, 'Pleural Effusion': None, 'Pleural Other': None, 'Fracture': None, 'Support Devices': None, 'No Finding': 1.0}
{'path_to_image': 'train/patient42142/study8/view1_frontal.jpg', 'Enlarged Cardiomediastinum': None, 'Cardiomegaly': None, 'Lung Opacity': None, 'Lung Lesion': None, 'Edema': None, 'Consolidation': None, 'Pneumonia': None, 'Atelectasis': None, 'Pneumothorax': None, 'Pleural Effusion': None, 'Pleural Other': None, 'Fracture': None, 'Support Devices': None, 'No Finding': 1.0}

======================================================================
impression_fixed.json
======================================================================
{'path_to_image': 'train/patient42142/study5/view1_frontal.jpg', 'Enlarged Cardiomediastinum': None, 'Cardiomegaly': None, 'Lung Opacity': 0.0, 'Lung Lesion': None, 'Edema': None, 'Consolidation': None, 'Pneumonia': None, 'Atelectasis': None, 'Pneumothorax': 0.0, 'Pleural Effusion': 0.0, 'Pleural Other': None, 'Fracture': None, 'Support Devices': 1.0, 'No Finding': None}
{'path_to_image': 'train/patient42142/study8/view1_frontal.jpg', 'Enlarged Cardiomediastinum': None, 'Cardiomegaly': None, 'Lung Opacity': None, 'Lung Lesion': None, 'Edema': None, 'Consolidation': None, 'Pneumonia': None, 'Atelectasis': 1.0, 'Pneumothorax': 0.0, 'Pleural Effusion': None, 'Pleural Other': None, 'Fracture': None, 'Support Devices': 1.0, 'No Finding': None}

======================================================================
report_fixed.json
======================================================================
{'path_to_image': 'train/patient42142/study5/view1_frontal.jpg', 'Enlarged Cardiomediastinum': None, 'Cardiomegaly': None, 'Lung Opacity': 0.0, 'Lung Lesion': None, 'Edema': None, 'Consolidation': None, 'Pneumonia': None, 'Atelectasis': None, 'Pneumothorax': 0.0, 'Pleural Effusion': 0.0, 'Pleural Other': None, 'Fracture': None, 'Support Devices': 1.0, 'No Finding': None}
{'path_to_image': 'train/patient42142/study8/view1_frontal.jpg', 'Enlarged Cardiomediastinum': None, 'Cardiomegaly': None, 'Lung Opacity': None, 'Lung Lesion': None, 'Edema': None, 'Consolidation': None, 'Pneumonia': None, 'Atelectasis': 1.0, 'Pneumothorax': 0.0, 'Pleural Effusion': None, 'Pleural Other': None, 'Fracture': None, 'Support Devices': 1.0, 'No Finding': None}

In [36]:
for filename in JSON_FILES:
    path = DATASET_ROOT / filename

    with open(path, "r") as f:
        record = json.loads(f.readline())

    print("\n", filename)
    print("Number of fields:", len(record))
    print("Fields:")

    for key in record.keys():
        print("  ", key)

 findings_fixed.json
Number of fields: 15
Fields:
   path_to_image
   Enlarged Cardiomediastinum
   Cardiomegaly
   Lung Opacity
   Lung Lesion
   Edema
   Consolidation
   Pneumonia
   Atelectasis
   Pneumothorax
   Pleural Effusion
   Pleural Other
   Fracture
   Support Devices
   No Finding

 impression_fixed.json
Number of fields: 15
Fields:
   path_to_image
   Enlarged Cardiomediastinum
   Cardiomegaly
   Lung Opacity
   Lung Lesion
   Edema
   Consolidation
   Pneumonia
   Atelectasis
   Pneumothorax
   Pleural Effusion
   Pleural Other
   Fracture
   Support Devices
   No Finding

 report_fixed.json
Number of fields: 15
Fields:
   path_to_image
   Enlarged Cardiomediastinum
   Cardiomegaly
   Lung Opacity
   Lung Lesion
   Edema
   Consolidation
   Pneumonia
   Atelectasis
   Pneumothorax
   Pleural Effusion
   Pleural Other
   Fracture
   Support Devices
   No Finding

In [37]:
for filename in JSON_FILES:
    path = DATASET_ROOT / filename

    with open(path, "r") as f:
        count = sum(1 for _ in f)

    print(filename, ":", count)

findings_fixed.json : 223462
impression_fixed.json : 223462
report_fixed.json : 223462

In [38]:
import json
from pathlib import Path

import pandas as pd


LABEL_COLUMNS = [
    "Enlarged Cardiomediastinum",
    "Cardiomegaly",
    "Lung Opacity",
    "Lung Lesion",
    "Edema",
    "Consolidation",
    "Pneumonia",
    "Atelectasis",
    "Pneumothorax",
    "Pleural Effusion",
    "Pleural Other",
    "Fracture",
    "Support Devices",
    "No Finding",
]


def load_label_json(path: str | Path) -> pd.DataFrame:
    """
    Load a CheXpert Plus fixed-label JSONL file.

    The file is read line-by-line to avoid unnecessary
    memory overhead.
    """
    records = []

    with open(path, "r") as f:
        for line in f:
            if line.strip():
                records.append(json.loads(line))

    return pd.DataFrame(records)

In [41]:
from dp_mmfl.data.labels import load_label_json

findings_df = load_label_json(
    DATASET_ROOT / "findings_fixed.json"
)

impression_df = load_label_json(
    DATASET_ROOT / "impression_fixed.json"
)

report_labels_df = load_label_json(
    DATASET_ROOT / "report_fixed.json"
)

ModuleNotFoundError: No module named 'dp_mmfl.data.labels'

In [42]:
%%writefile /content/DP-MMFL/src/dp_mmfl/data/labels.py
import json
from pathlib import Path
import pandas as pd

LABEL_COLUMNS = [
    "Enlarged Cardiomediastinum",
    "Cardiomegaly",
    "Lung Opacity",
    "Lung Lesion",
    "Edema",
    "Consolidation",
    "Pneumonia",
    "Atelectasis",
    "Pneumothorax",
    "Pleural Effusion",
    "Pleural Other",
    "Fracture",
    "Support Devices",
    "No Finding",
]

def load_label_json(path: str | Path) -> pd.DataFrame:
    """
    Load a CheXpert Plus fixed-label JSONL file.

    The file is read line-by-line to avoid unnecessary
    memory overhead.
    """
    records = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line_str = line.strip()
            if line_str:
                records.append(json.loads(line_str))

    return pd.DataFrame(records)

Writing /content/DP-MMFL/src/dp_mmfl/data/labels.py

In [43]:
import sys
from pathlib import Path

if "/content/DP-MMFL/src" not in sys.path:
    sys.path.append("/content/DP-MMFL/src")

from dp_mmfl.data.labels import load_label_json, LABEL_COLUMNS

# Assumes DATASET_ROOT is already defined as Path("/content/drive/MyDrive/DP-MMFL/data/raw/CheXpertPlus")
findings_df = load_label_json(DATASET_ROOT / "findings_fixed.json")
impression_df = load_label_json(DATASET_ROOT / "impression_fixed.json")
report_labels_df = load_label_json(DATASET_ROOT / "report_fixed.json")

print("Shape Verifications:")
print(f"Findings:   {findings_df.shape}")
print(f"Impression: {impression_df.shape}")
print(f"Report:     {report_labels_df.shape}")

Shape Verifications:
Findings:   (223462, 15)
Impression: (223462, 15)
Report:     (223462, 15)

In [44]:
csv_paths = set(df["path_to_image"])
findings_paths = set(findings_df["path_to_image"])
impression_paths = set(impression_df["path_to_image"])
report_paths = set(report_labels_df["path_to_image"])

print(f"Unique CSV paths:        {len(csv_paths)}")
print(f"Unique Findings paths:   {len(findings_paths)}")
print(f"Unique Impression paths: {len(impression_paths)}")
print(f"Unique Report paths:     {len(report_paths)}")

print("\nIntersections with CSV:")
print(f"CSV ∩ Findings:   {len(csv_paths & findings_paths)}")
print(f"CSV ∩ Impression: {len(csv_paths & impression_paths)}")
print(f"CSV ∩ Report:     {len(csv_paths & report_paths)}")

print("\nMissing Key Check (Target: 0):")
print(f"CSV paths missing from findings:   {len(csv_paths - findings_paths)}")
print(f"CSV paths missing from impression: {len(csv_paths - impression_paths)}")
print(f"CSV paths missing from report:     {len(csv_paths - report_paths)}")

Unique CSV paths:        223462
Unique Findings paths:   223462
Unique Impression paths: 223462
Unique Report paths:     223462

Intersections with CSV:
CSV ∩ Findings:   223462
CSV ∩ Impression: 223462
CSV ∩ Report:     223462

Missing Key Check (Target: 0):
CSV paths missing from findings:   0
CSV paths missing from impression: 0
CSV paths missing from report:     0

In [45]:
for name, dataset in [
    ("CSV", df),
    ("Findings", findings_df),
    ("Impression", impression_df),
    ("Report", report_labels_df),
]:
    duplicates = dataset["path_to_image"].duplicated().sum()
    print(f"{name:<12}: {duplicates} duplicate paths")

CSV         : 0 duplicate paths
Findings    : 0 duplicate paths
Impression  : 0 duplicate paths
Report      : 0 duplicate paths

In [46]:
import pandas as pd

label_counts = pd.DataFrame({
    "findings_notna": findings_df[LABEL_COLUMNS].notna().sum(),
    "impression_notna": impression_df[LABEL_COLUMNS].notna().sum(),
    "report_notna": report_labels_df[LABEL_COLUMNS].notna().sum(),
})
print(label_counts.to_string())

                            findings_notna  impression_notna  report_notna
Enlarged Cardiomediastinum           23967             45102         61189
Cardiomegaly                         23786             50639         69191
Lung Opacity                         33951            108361        117615
Lung Lesion                           4278             12274         15983
Edema                                19278             86457         90358
Consolidation                        17180             71781         76072
Pneumonia                             4998             27536         33728
Atelectasis                          17674             68979         74295
Pneumothorax                         25670             78928         89232
Pleural Effusion                     37378            133171        145504
Pleural Other                         2435              6815          8781
Fracture                              6164             13127         16287
Support Devices                      32088            119923        135595
No Finding                          167933             21259         13053

In [47]:
def count_differences(df_a, df_b, cols):
    a = df_a[cols]
    b = df_b[cols]
    both_nan = a.isna() & b.isna()
    # Mismatch occurs when values differ and they are not both NaN
    diff_mask = (~both_nan) & (a != b)
    return diff_mask.to_numpy().sum()

pairs = [
    ("Findings", findings_df, "Impression", impression_df),
    ("Findings", findings_df, "Report", report_labels_df),
    ("Impression", impression_df, "Report", report_labels_df),
]

for name_a, data_a, name_b, data_b in pairs:
    diff_count = count_differences(data_a, data_b, LABEL_COLUMNS)
    print(f"{name_a} vs {name_b}: {diff_count:,} total differing label cells")

Findings vs Impression: 970,104 total differing label cells
Findings vs Report: 1,167,300 total differing label cells
Impression vs Report: 1,176,685 total differing label cells

In [48]:
import pandas as pd

print("--- Positive Label Prevalence (report_fixed) ---")
positive_rates = (report_labels_df[LABEL_COLUMNS] == 1.0).mean().sort_values()

prevalence_summary = pd.DataFrame({
    "positive_rate": positive_rates,
    "positive_count": (report_labels_df[LABEL_COLUMNS] == 1.0).sum()[positive_rates.index],
    "negative_count": (report_labels_df[LABEL_COLUMNS] == 0.0).sum()[positive_rates.index],
    "nan_count": report_labels_df[LABEL_COLUMNS].isna().sum()[positive_rates.index],
})

print(prevalence_summary.to_string())

--- Positive Label Prevalence (report_fixed) ---
                            positive_rate  positive_count  negative_count  nan_count
Pleural Other                    0.025776            5760              50     214681
Pneumonia                        0.026685            5963            4720     189734
Enlarged Cardiomediastinum       0.040906            9141           32721     162273
Fracture                         0.049865           11143            4594     207175
No Finding                       0.058413           13053               0     210409
Lung Lesion                      0.058842           13149            1473     207479
Consolidation                    0.065823           14709           33262     147390
Pneumothorax                     0.085634           19136           67218     134230
Cardiomegaly                     0.161871           36172           25996     154271
Atelectasis                      0.171318           38283             745     149167
Edema                            0.242793           54255           23071     133104
Pleural Effusion                 0.420993           94076           43956      77958
Lung Opacity                     0.494849          110580            6485     105847
Support Devices                  0.596441          133282            2279      87867

In [49]:
for label in LABEL_COLUMNS:
    counts = report_labels_df[label].value_counts(dropna=False)

    print("\n" + "=" * 50)
    print(label)
    print("=" * 50)
    print(counts)

==================================================
Enlarged Cardiomediastinum
==================================================
Enlarged Cardiomediastinum
 NaN    162273
 0.0     32721
-1.0     19327
 1.0      9141
Name: count, dtype: int64

==================================================
Cardiomegaly
==================================================
Cardiomegaly
 NaN    154271
 1.0     36172
 0.0     25996
-1.0      7023
Name: count, dtype: int64

==================================================
Lung Opacity
==================================================
Lung Opacity
 1.0    110580
 NaN    105847
 0.0      6485
-1.0       550
Name: count, dtype: int64

==================================================
Lung Lesion
==================================================
Lung Lesion
 NaN    207479
 1.0     13149
 0.0      1473
-1.0      1361
Name: count, dtype: int64

==================================================
Edema
==================================================
Edema
 NaN    133104
 1.0     54255
 0.0     23071
-1.0     13032
Name: count, dtype: int64

==================================================
Consolidation
==================================================
Consolidation
 NaN    147390
 0.0     33262
-1.0     28101
 1.0     14709
Name: count, dtype: int64

==================================================
Pneumonia
==================================================
Pneumonia
 NaN    189734
-1.0     23045
 1.0      5963
 0.0      4720
Name: count, dtype: int64

==================================================
Atelectasis
==================================================
Atelectasis
 NaN    149167
 1.0     38283
-1.0     35267
 0.0       745
Name: count, dtype: int64

==================================================
Pneumothorax
==================================================
Pneumothorax
 NaN    134230
 0.0     67218
 1.0     19136
-1.0      2878
Name: count, dtype: int64

==================================================
Pleural Effusion
==================================================
Pleural Effusion
 1.0    94076
 NaN    77958
 0.0    43956
-1.0     7472
Name: count, dtype: int64

==================================================
Pleural Other
==================================================
Pleural Other
 NaN    214681
 1.0      5760
-1.0      2971
 0.0        50
Name: count, dtype: int64

==================================================
Fracture
==================================================
Fracture
 NaN    207175
 1.0     11143
 0.0      4594
-1.0       550
Name: count, dtype: int64

==================================================
Support Devices
==================================================
Support Devices
 1.0    133282
 NaN     87867
 0.0      2279
-1.0        34
Name: count, dtype: int64

==================================================
No Finding
==================================================
No Finding
NaN    210409
1.0     13053
Name: count, dtype: int64

In [50]:
LABEL_COLUMNS = [
    "Enlarged Cardiomediastinum",
    "Cardiomegaly",
    "Lung Opacity",
    "Lung Lesion",
    "Edema",
    "Consolidation",
    "Pneumonia",
    "Atelectasis",
    "Pneumothorax",
    "Pleural Effusion",
    "Pleural Other",
    "Fracture",
    "Support Devices",
    "No Finding",
]

label_state_summary = []

for label in LABEL_COLUMNS:
    counts = report_labels_df[label].value_counts(dropna=False)

    label_state_summary.append({
        "label": label,
        "positive_1": counts.get(1.0, 0),
        "negative_0": counts.get(0.0, 0),
        "uncertain_-1": counts.get(-1.0, 0),
        "missing_nan": counts.get(float("nan"), 0),
    })

label_state_summary = pd.DataFrame(label_state_summary)

label_state_summary

,label,positive_1,negative_0,uncertain_-1,missing_nan
0,Enlarged Cardiomediastinum,9141,32721,19327,162273
1,Cardiomegaly,36172,25996,7023,154271
2,Lung Opacity,110580,6485,550,105847
3,Lung Lesion,13149,1473,1361,207479
4,Edema,54255,23071,13032,133104
5,Consolidation,14709,33262,28101,147390
6,Pneumonia,5963,4720,23045,189734
7,Atelectasis,38283,745,35267,149167
8,Pneumothorax,19136,67218,2878,134230
9,Pleural Effusion,94076,43956,7472,77958
10,Pleural Other,5760,50,2971,214681
11,Fracture,11143,4594,550,207175
12,Support Devices,133282,2279,34,87867
13,No Finding,13053,0,0,210409

In [51]:
rows = []

for label in LABEL_COLUMNS:
    s = report_labels_df[label]

    rows.append({
        "label": label,
        "positive_1": (s == 1.0).sum(),
        "negative_0": (s == 0.0).sum(),
        "uncertain_-1": (s == -1.0).sum(),
        "missing_nan": s.isna().sum(),
    })

label_state_summary = pd.DataFrame(rows)

print(label_state_summary.to_string(index=False))

                     label  positive_1  negative_0  uncertain_-1  missing_nan
Enlarged Cardiomediastinum        9141       32721         19327       162273
              Cardiomegaly       36172       25996          7023       154271
              Lung Opacity      110580        6485           550       105847
               Lung Lesion       13149        1473          1361       207479
                     Edema       54255       23071         13032       133104
             Consolidation       14709       33262         28101       147390
                 Pneumonia        5963        4720         23045       189734
               Atelectasis       38283         745         35267       149167
              Pneumothorax       19136       67218          2878       134230
          Pleural Effusion       94076       43956          7472        77958
             Pleural Other        5760          50          2971       214681
                  Fracture       11143        4594           550       207175
           Support Devices      133282        2279            34        87867
                No Finding       13053           0             0       210409

In [52]:
label_state_summary["known_count"] = (
    label_state_summary["positive_1"]
    + label_state_summary["negative_0"]
)

label_state_summary["positive_rate_known"] = (
    label_state_summary["positive_1"]
    / label_state_summary["known_count"]
)

print(
    label_state_summary[
        [
            "label",
            "positive_1",
            "negative_0",
            "uncertain_-1",
            "missing_nan",
            "known_count",
            "positive_rate_known",
        ]
    ].to_string(index=False)
)

                     label  positive_1  negative_0  uncertain_-1  missing_nan  known_count  positive_rate_known
Enlarged Cardiomediastinum        9141       32721         19327       162273        41862             0.218360
              Cardiomegaly       36172       25996          7023       154271        62168             0.581843
              Lung Opacity      110580        6485           550       105847       117065             0.944603
               Lung Lesion       13149        1473          1361       207479        14622             0.899261
                     Edema       54255       23071         13032       133104        77326             0.701640
             Consolidation       14709       33262         28101       147390        47971             0.306623
                 Pneumonia        5963        4720         23045       189734        10683             0.558177
               Atelectasis       38283         745         35267       149167        39028             0.980911
              Pneumothorax       19136       67218          2878       134230        86354             0.221599
          Pleural Effusion       94076       43956          7472        77958       138032             0.681552
             Pleural Other        5760          50          2971       214681         5810             0.991394
                  Fracture       11143        4594           550       207175        15737             0.708077
           Support Devices      133282        2279            34        87867       135561             0.983188
                No Finding       13053           0             0       210409        13053             1.000000

In [53]:
print(
    report_labels_df["No Finding"]
    .value_counts(dropna=False)
)

No Finding
NaN    210409
1.0     13053
Name: count, dtype: int64

In [54]:
TARGET_COLUMNS = [
    "Enlarged Cardiomediastinum",
    "Cardiomegaly",
    "Lung Opacity",
    "Lung Lesion",
    "Edema",
    "Consolidation",
    "Pneumonia",
    "Atelectasis",
    "Pneumothorax",
    "Pleural Effusion",
    "Pleural Other",
    "Fracture",
    "Support Devices",
]

In [55]:
%%writefile /content/DP-MMFL/src/dp_mmfl/data/labels.py
import json
from pathlib import Path
import numpy as np
import pandas as pd

TARGET_COLUMNS = [
    "Enlarged Cardiomediastinum",
    "Cardiomegaly",
    "Lung Opacity",
    "Lung Lesion",
    "Edema",
    "Consolidation",
    "Pneumonia",
    "Atelectasis",
    "Pneumothorax",
    "Pleural Effusion",
    "Pleural Other",
    "Fracture",
    "Support Devices",
]

ALL_LABEL_COLUMNS = TARGET_COLUMNS + ["No Finding"]

def load_label_json(path: str | Path) -> pd.DataFrame:
    """
    Load a line-delimited JSON label file.
    Each line contains one JSON object corresponding to one image.
    """
    records = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line_str = line.strip()
            if line_str:
                records.append(json.loads(line_str))
    return pd.DataFrame(records)

def apply_label_policy(
    labels_df: pd.DataFrame,
    target_columns: list[str] | None = None,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    """
    Apply the primary uncertainty policy (U-Ignore).

    Label semantics:
        1.0  -> positive
        0.0  -> negative
        -1.0 -> uncertain -> ignored
        NaN  -> missing   -> ignored

    Returns:
        targets: DataFrame containing 0/1 targets and NaN for ignored labels
        masks:   DataFrame containing 1 where the label contributes to loss,
                 0 where the label is ignored
    """
    if target_columns is None:
        target_columns = TARGET_COLUMNS

    targets = pd.DataFrame(index=labels_df.index)
    masks = pd.DataFrame(index=labels_df.index)

    for label in target_columns:
        values = labels_df[label]

        # Only explicit positive (1.0) and negative (0.0) labels are used for supervision
        targets[label] = values.where(
            values.isin([0.0, 1.0]),
            np.nan,
        )

        # 1 = valid supervised target, 0 = uncertain (-1.0) or missing (NaN)
        masks[label] = values.isin([0.0, 1.0]).astype(np.int8)

    return targets, masks

Overwriting /content/DP-MMFL/src/dp_mmfl/data/labels.py

In [56]:
import os
from google.colab import userdata

# Navigate to the repo
%cd /content/DP-MMFL

# Configure git credentials if not already set
!git config --global user.name "PreethamHD"
!git config --global user.email "preethamgowda837@gmail.com"

# Set authenticated URL via Colab secret or manual token
try:
    token = userdata.get("GITHUB_TOKEN")
    !git remote set-url origin https://{token}@github.com/PreethamHD/DP-MMFL.git
except Exception:
    pass

# Stage all tracked and new code/config files
!git add src/ configs/ docs/ .gitignore

# Commit changes
!git commit -m "feat(phase-1): update label policies and manifest utilities"

# Push to main
!git push origin main

# Confirm working tree is clean
!git status

/content/DP-MMFL
[main 5645932] feat(phase-1): update label policies and manifest utilities
 2 files changed, 73 insertions(+)
 create mode 100644 src/dp_mmfl/data/labels.py
Enumerating objects: 14, done.
Counting objects: 100% (14/14), done.
Delta compression using up to 2 threads
Compressing objects: 100% (7/7), done.
Writing objects: 100% (8/8), 1.44 KiB | 1.44 MiB/s, done.
Total 8 (delta 4), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
To https://github.com/PreethamHD/DP-MMFL.git
   7162d7e..5645932  main -> main
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean